config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get 'tweets/mentions' => 'tweets#mentions', as: :mentions
  get 'tweets/mentions_by_user' => 'tweets#mentions_by_user', as: :mentions_by_user
  get 'about' => 'about#index', as: :about

end

app/models/tweet.rb
class Tweet
  include ActiveModel::Model

  def initialize(tweet)
    @tweet = tweet
  end

  def id
    @tweet['id_str']
  end

  def content
    @tweet['text']
  end

  def in_reply_to
    @tweet['in_reply_to_user_id_str']
  end

  def not_in_reply_to? (user_id)
    in_reply_to != user_id
  end

  def followers_count
    user['followers_count']
  end

  def user_name
    user['name']
  end

  def user
    @tweet['user']
  end

  def user_screen_name
    user['screen_name']
  end

  def mentioned?(user_id)
    !@tweet['entities']['user_mentions'].select {|mention| mention['id_str'] == user_id}.empty?
  end

  def retweet_count
    @tweet['retweet_count'].to_i
  end

  def favorite_count
    @tweet['favorite_count'] || 0
  end

  def created_at
    DateTime.parse(user['created_at'])
  end

  def classification_by_favorite_count(other)
    favorite_count <=> other.favorite_count
  end

  def classification_by_retweet_count(other)
    retweet_count <=> other.retweet_count
  end

  def classification_by_followers_count(other)
    followers_count <=> other.followers_count
  end

  def classification(other)
    classification_by_retweet_count(other) + classification_by_followers_count(other) + classification_by_favorite_count(other)
  end

  def <=>(other)
    classification(other)
  end

  def ==(other)
    id == other.id
  end

  def to_s
    "Tweet##{id}"
  end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  respond_to :html
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  ensure_security_headers # See more: https://github.com/twitter/secureheaders

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  respond_to :html

  def index
    redirect_to mentions_url
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  respond_to :html

  def mentions
    @tweets = TweetsPresenter.new tweets_mentions
  end

  def mentions_by_user
    @users = UsersPresenter.new TwitterService.mentions_by_user
  end

  private

  def tweets_mentions
    TwitterService.mentions
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def item_menu(title, path)
    content_tag(:li, link_to(I18n.t(title), path), :class => (current_page?(path) ? 'active' : ''))
  end

end

app/views/about/index.html.slim
.well.text-center
  h1
    | Pai, marido e desenvolvedor. Apaixonado pelo que faz =]
  h5
    | Clique nos links abaixo e conheça um pouco mais

  ul.list-inline
    li = link_to(icon('github', '', class: 'fa-3x'), 'http://github.com/ddomingues')
    li = link_to(icon('twitter', '', class: 'fa-3x'), 'http://twitter.com/diegohdomingues')
    li = link_to(icon('linkedin', '', class: 'fa-3x'), 'http://br.linkedin.com/in/diegohdomingues')

  h3 ;)

app/views/application/_flash_messages.html.slim
- flash.each do |key, value|
  div id="flash_#{key}"
    = value

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top role="navigation"
  .container
    .navbar-header
      button.navbar-toggle.collapsed data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to root_path, class: 'navbar-brand' do
        span.fa.fa-twitter.fa-lg.blue
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        = item_menu 'tweets.mentions.title', mentions_path
        = item_menu 'tweets.mentions_by_user.title', mentions_by_user_path
      ul.nav.navbar-nav.navbar-right
        = item_menu 'about.index.title', about_path

app/views/layouts/application.html.slim
doctype 5
html lang="pt"
  head
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1"
    meta charset="utf-8"
    meta name="keywords" content="twitter"
    meta name="description" content=""
    meta name="author" content="Diego Domingues">

    title
      = page_title(app_name: 'Twitter')

    link href="/favicon.ico" rel=("shortcut icon")

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

    /![if lt IE 9]
      script src="http://html5shim.googlecode.com/svn/trunk/html5.js"

  body class=body_class
    = render :partial => 'layouts/navigation'
    .container
      = render 'flash_messages'
      = yield

app/views/shared/_navigation.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top role="navigation"
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed.active data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand.active href="#"  Menções no Twitter
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        li
          a href="#"  Usuários que mais mencionam
      ul.nav.navbar-nav.navbar-right
        li
          a href="#"  Sobre

app/views/tweets/_tweet.html.slim
article.row.tweet
  .col-sm-12.col-md-12.col-xs-12
    .caption
      = link_to tweet.url do
        h3
          = tweet.user_name
          small = " #{tweet.user_screen_name} #{I18n.l(tweet.created_at, :format => :long)}"
      p = tweet.content
      ul.list-inline
        = tweet.retweet_count
        = tweet.favorite_count
        = tweet.followers_count

app/views/tweets/_user.html.slim
article.row.user
  .col-sm-12.col-md-12.col-xs-12
    .caption
      = link_to user.perfil_url do
        h3
          = user.name
          small
            = " #{user.screen_name} - "
            = icon('twitter', user.tweets_count, class: 'blue')

    = render user.tweets

app/views/tweets/mentions.html.slim
.panel.panel-default.row
  .panel-heading
    = I18n.t('tweets.mentions.panel-title')
  .panel-body
    = render @tweets

app/views/tweets/mentions_by_user.html.slim
.panel.panel-default.row
  .panel-heading
    = I18n.t('tweets.mentions_by_user.panel-title')
  .panel-body
    = render @users